### ISSUE TITLE
Avoid errors when CKAN package is created

### ISSUE THREAD

**Issue by avdata99** [datopian/ckan-ng-harvester-core#2]
The CKAN [create_package function](https://github.com/datopian/ckan-ng-harvester-core/blob/master/harvester_adapters/ckan/api.py#L256:L256)

Add to the _on_duplicated=SKIP_ option the data of the resource

### Tasks

* [x] Use package_show or some api call to get the data from the already existing package
* [x] Send as _['result']_ key in response

**Comment by estebanruseler** [comment]
When fixing the harvester duplication error, Andres encountered 2 small bugs (#2 and #3). They are fixed and PR is with Adam
